-- Runs inside the built Pandoc: every native module must load into its Lua state.
assert(_VERSION == 'Lua 5.4')
local sqlite = require('lsqlite3')
local db = assert(sqlite.open_memory())
assert(type(db) == 'userdata', 'SQLite must be a native module')
assert(db:exec('CREATE TABLE t (value); INSERT INTO t VALUES (42)') == sqlite.OK)
for row in db:nrows('SELECT value FROM t') do assert(row.value == 42) end
db:close()
local uv = require('luv')
assert(uv.fs_stat('.').type == 'directory')
local fired = false
local timer = uv.new_timer()
timer:start(1, 0, function() fired = true; timer:close() end)
uv.run()
assert(fired, 'native libuv callback did not run')
assert(require('luaamath').to_mathml('x^2') == '<msup><mi>x</mi><mn>2</mn></msup>')
local zip = require('brimworks.zip')
pandoc.system.with_temporary_directory('specc-native', function(dir)
    local path = dir .. '/roundtrip.zip'
    local archive = assert(zip.open(path, zip.CREATE + zip.EXCL))
    archive:add('hello.txt', 'string', 'hello')
    archive:close()
    archive = assert(zip.open(path))
    local entry = assert(archive:open('hello.txt'))
    assert(entry:read(5) == 'hello')
    entry:close()
    archive:close()
end)
print('Native Lua modules loaded successfully inside Pandoc')
