---Clean DOCX preset for sw_docs examples.
---@module preset

return {
    name = "SW Docs Clean",
    description = "Compact modern style for rendered software specification examples",

    page = {
        size = "A4",
        orientation = "portrait",
        margins = {
            top = "0.75in",
            bottom = "0.75in",
            left = "0.85in",
            right = "0.85in",
        },
    },

    paragraph_styles = {
        {
            id = "Normal",
            name = "Normal",
            font = { name = "Liberation Sans", size = 10.5, color = "1F2937" },
            spacing = { line = 1.12, after = 6 },
            indent = { first_line = "0in" },
            alignment = "left",
        },
        {
            id = "Heading1",
            name = "Heading 1",
            based_on = "Normal",
            next = "FirstParagraph",
            font = { name = "Liberation Sans", size = 16, bold = true, color = "111827" },
            spacing = { before = 14, after = 4, line = 1.05 },
            indent = { first_line = "0in" },
            keep_next = true,
            page_break_before = true,
            outline_level = 0,
        },
        {
            id = "Heading2",
            name = "Heading 2",
            based_on = "Normal",
            next = "FirstParagraph",
            font = { name = "Liberation Sans", size = 13, bold = true, color = "0F3D4C" },
            spacing = { before = 10, after = 3, line = 1.08 },
            indent = { first_line = "0in" },
            keep_next = true,
            outline_level = 1,
        },
        {
            id = "Heading3",
            name = "Heading 3",
            based_on = "Normal",
            next = "FirstParagraph",
            font = { name = "Liberation Sans", size = 11, bold = true, color = "1F2937" },
            spacing = { before = 8, after = 2, line = 1.08 },
            indent = { first_line = "0in" },
            keep_next = true,
            outline_level = 2,
        },
        {
            id = "Heading4",
            name = "Heading 4",
            based_on = "Normal",
            next = "FirstParagraph",
            font = { name = "Liberation Sans", size = 10.5, bold = true, italic = true, color = "374151" },
            spacing = { before = 6, after = 2, line = 1.08 },
            indent = { first_line = "0in" },
            keep_next = true,
            outline_level = 3,
        },
        {
            id = "Heading5",
            name = "Heading 5",
            based_on = "Normal",
            next = "FirstParagraph",
            font = { name = "Liberation Sans", size = 10.5, bold = true, color = "4B5563" },
            spacing = { before = 6, after = 2, line = 1.08 },
            indent = { first_line = "0in" },
            keep_next = true,
            outline_level = 4,
        },
        {
            id = "Title",
            name = "Title",
            based_on = "Normal",
            next = "FirstParagraph",
            font = { name = "Liberation Sans", size = 22, bold = true, color = "0F172A" },
            spacing = { after = 8, line = 1.0 },
            indent = { first_line = "0in" },
            alignment = "left",
        },
        {
            id = "Caption",
            name = "Caption",
            based_on = "Normal",
            font = { name = "Liberation Sans", size = 8.5, italic = true, color = "4B5563" },
            spacing = { before = 2, after = 8, line = 1.0 },
            indent = { first_line = "0in" },
            alignment = "center",
        },
        {
            id = "Quote",
            name = "Quote",
            based_on = "Normal",
            font = { name = "Liberation Sans", size = 10.5, italic = true, color = "374151" },
            spacing = { line = 1.12, before = 6, after = 6 },
            indent = { left = "0.25in", right = "0.25in", first_line = "0in" },
            borders = {
                left = { style = "single", width = 1.5, color = "B6CDD6", space = 4 },
            },
        },
        {
            id = "FirstParagraph",
            name = "First Paragraph",
            based_on = "Normal",
            next = "Normal",
            font = { name = "Liberation Sans", size = 10.5, color = "1F2937" },
            spacing = { line = 1.12, after = 6 },
            indent = { first_line = "0in" },
            alignment = "left",
        },
        {
            id = "BodyText",
            name = "Body Text",
            based_on = "Normal",
            font = { name = "Liberation Sans", size = 10.5, color = "1F2937" },
            spacing = { line = 1.12, after = 6 },
            indent = { first_line = "0in" },
            alignment = "left",
        },
        {
            id = "Header",
            name = "Header",
            based_on = "Normal",
            font = { name = "Liberation Sans", size = 8.5, color = "6B7280" },
            spacing = { line = 1.0, after = 0 },
            indent = { first_line = "0in" },
        },
        {
            id = "Footer",
            name = "Footer",
            based_on = "Normal",
            font = { name = "Liberation Sans", size = 8.5, color = "6B7280" },
            spacing = { line = 1.0, after = 0 },
            indent = { first_line = "0in" },
        },
        {
            id = "Source",
            name = "Source",
            based_on = "Normal",
            font = { name = "Liberation Sans", size = 8.5, color = "6B7280" },
            spacing = { before = 0, after = 5, line = 1.0 },
            indent = { first_line = "0in" },
            alignment = "center",
        },
        {
            id = "Reference",
            name = "Reference",
            based_on = "Normal",
            font = { name = "Liberation Sans", size = 10.5, color = "1F2937" },
            spacing = { before = 0, after = 5, line = 1.12 },
            indent = { hanging = "0.35in", left = "0.35in" },
        },
        {
            id = "SourceCode",
            name = "Source Code",
            based_on = "Normal",
            font = { name = "Liberation Mono", size = 8.8, color = "111827" },
            spacing = { before = 0, after = 0, line = 1.0 },
            indent = { first_line = "0in", left = "0.06in", right = "0.06in" },
            alignment = "left",
            borders = {
                top    = { style = "single", width = 0.5, color = "D1D5DB" },
                bottom = { style = "single", width = 0.5, color = "D1D5DB" },
                left   = { style = "single", width = 0.5, color = "D1D5DB" },
                right  = { style = "single", width = 0.5, color = "D1D5DB" },
            },
            shading = { pattern = "clear", fill = "F8FAFC" },
        },
        {
            id = "SpecObjectHeader",
            name = "Spec Object Header",
            based_on = "Normal",
            next = "FirstParagraph",
            font = { name = "Liberation Sans", size = 12.5, bold = true, color = "0F4C64" },
            spacing = { before = 10, after = 4, line = 1.08 },
            indent = { first_line = "0in" },
            keep_next = true,
            outline_level = 0,
            borders = {
                bottom = { style = "single", width = 0.5, color = "CFE3EA", space = 2 },
            },
        },
        {
            id = "FigureCenter",
            name = "Figure Center",
            based_on = "Normal",
            alignment = "center",
            spacing = { before = 5, after = 5, line = 1.0 },
            indent = { first_line = "0in" },
        },
        {
            id = "TOCHeading",
            name = "TOC Heading",
            based_on = "Normal",
            next = "Normal",
            font = { name = "Liberation Sans", size = 16, bold = true, color = "111827" },
            spacing = { before = 0, after = 6, line = 1.08 },
            indent = { first_line = "0in" },
            alignment = "left",
        },
        {
            id = "TOC1",
            name = "TOC 1",
            based_on = "Normal",
            font = { name = "Liberation Sans", size = 10.5, bold = true, color = "1F2937" },
            spacing = { before = 4, after = 0, line = 1.08 },
            indent = { first_line = "0in" },
        },
        {
            id = "TOC2",
            name = "TOC 2",
            based_on = "Normal",
            font = { name = "Liberation Sans", size = 10, color = "374151" },
            spacing = { before = 0, after = 0, line = 1.08 },
            indent = { left = "0.2in", first_line = "0in" },
        },
        {
            id = "TOC3",
            name = "TOC 3",
            based_on = "Normal",
            font = { name = "Liberation Sans", size = 10, color = "4B5563" },
            spacing = { before = 0, after = 0, line = 1.08 },
            indent = { left = "0.4in", first_line = "0in" },
        },
        {
            id = "CoverTitle",
            name = "Cover Title",
            based_on = "Normal",
            font = { name = "Liberation Sans", size = 24, bold = true, color = "0F172A" },
            spacing = { before = 0, after = 10, line = 1.0 },
            indent = { first_line = "0in" },
            alignment = "center",
        },
        {
            id = "CoverSubtitle",
            name = "Cover Subtitle",
            based_on = "Normal",
            font = { name = "Liberation Sans", size = 14, color = "4B5563" },
            spacing = { before = 0, after = 8, line = 1.0 },
            indent = { first_line = "0in" },
            alignment = "center",
        },
        {
            id = "CoverAuthor",
            name = "Cover Author",
            based_on = "Normal",
            font = { name = "Liberation Sans", size = 10.5, color = "1F2937" },
            spacing = { before = 0, after = 4, line = 1.0 },
            indent = { first_line = "0in" },
            alignment = "center",
        },
        {
            id = "CoverDate",
            name = "Cover Date",
            based_on = "Normal",
            font = { name = "Liberation Sans", size = 10, italic = true, color = "6B7280" },
            spacing = { before = 0, after = 4, line = 1.0 },
            indent = { first_line = "0in" },
            alignment = "center",
        },
        {
            id = "CoverDocId",
            name = "Cover Document ID",
            based_on = "Normal",
            font = { name = "Liberation Sans", size = 9, color = "9CA3AF" },
            spacing = { before = 0, after = 4, line = 1.0 },
            indent = { first_line = "0in" },
            alignment = "center",
        },
        {
            id = "CoverVersion",
            name = "Cover Version",
            based_on = "Normal",
            font = { name = "Liberation Sans", size = 9, color = "9CA3AF" },
            spacing = { before = 0, after = 4, line = 1.0 },
            indent = { first_line = "0in" },
            alignment = "center",
        },
    },

    character_styles = {
        {
            id = "VerbatimChar",
            name = "Verbatim Char",
            font = { name = "Liberation Mono", size = 9, color = "111827" },
        },
        {
            id = "Hyperlink",
            name = "Hyperlink",
            font = { name = "Liberation Sans", color = "2563EB", underline = true },
        },
    },

    floats = {
        source_self_text = "Autor",
        source_style = "Source",
        source_template = "Fonte: %s",
    },

    captions = {
        figure = {
            template = "{prefix} {number}: {title}",
            prefix = "Figura",
            separator = ": ",
            style = "Caption",
            position = "below",
            source_style = "Source",
        },
        plantuml = {
            template = "{prefix} {number}: {title}",
            prefix = "Figura",
            separator = ": ",
            style = "Caption",
            position = "below",
            source_style = "Source",
        },
        table = {
            template = "{prefix} {number}: {title}",
            prefix = "Tabela",
            separator = ": ",
            style = "Caption",
            position = "above",
            source_style = "Source",
        },
        listing = {
            template = "{prefix} {number}: {title}",
            prefix = "Quadro",
            separator = ": ",
            style = "Caption",
            position = "above",
            source_style = "Source",
        },
    },

    settings = {
        default_tab_stop = 720,
        language = "pt-BR",
    },
}
